# Generated by Django 4.2.4 on 2023-08-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemNo', models.CharField(blank=True, max_length=50, null=True)),
                ('qnty', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Description2', models.CharField(blank=True, max_length=200, null=True)),
                ('SearchDescription', models.CharField(blank=True, max_length=200, null=True)),
                ('LotSize', models.IntegerField(blank=True, null=True)),
                ('Blocked', models.BooleanField(blank=True, null=True)),
                ('CompoundNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('Material', models.CharField(blank=True, max_length=50, null=True)),
                ('Durometer', models.CharField(blank=True, max_length=50, null=True)),
                ('DurometerScale', models.CharField(blank=True, max_length=50, null=True)),
                ('DurometerRange', models.CharField(blank=True, max_length=50, null=True)),
                ('Color', models.CharField(blank=True, max_length=50, null=True)),
                ('LowTemperature', models.CharField(blank=True, max_length=50, null=True)),
                ('HighTemperature', models.CharField(blank=True, max_length=50, null=True)),
                ('FDACompliant', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
