# Generated by Django 4.2.4 on 2023-08-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_a3sanitary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SteamResistant',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
