# Generated by Django 4.2.4 on 2023-08-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_steamresistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ConductiveFiller',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='CrossSectionalGeometry',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ExternallyLubricated',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='InternallyLubricated',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='LowCompressionSet',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='UltraSteamResistant',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
