# Generated by Django 4.2.4 on 2023-08-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='picture',
            new_name='picture1',
        ),
        migrations.AddField(
            model_name='product',
            name='picture2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
