# Generated by Django 4.2.4 on 2023-09-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_product_crosssectionaldiameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CrossSectionalDiameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='InsideDiameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='SizeAS568',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
