# Generated by Django 4.2.4 on 2023-09-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_product_crosssectionaldiameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SizeAS568',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
