# Generated by Django 4.2.4 on 2023-09-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_product_sizeas568'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SizeAS568',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
