# Generated by Django 4.2.4 on 2023-09-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_product_sizeas568'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CrossSectionalDiameter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='InsideDiameter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='SizeAS568',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
