# Generated by Django 4.2.5 on 2023-09-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_product_crosssectionaldiameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture1',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture2',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
